"""message

Revision ID: 0ea66bcf6bb2
Revises: 03a97d8a1ce9
Create Date: 2024-11-24 19:01:44.910322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea66bcf6bb2'
down_revision = '03a97d8a1ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
