"""message

Revision ID: 427ab59a7afa
Revises: 0ea66bcf6bb2
Create Date: 2024-11-24 19:10:50.626392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427ab59a7afa'
down_revision = '0ea66bcf6bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
